# Site settings
title: JC
email: jacrowley@ucdavis.edu
url: https://jacrowley-lin.github.io/
description: "Personal Website for JC, Phd Student at UC Davis"
keywords: "your keywords, separated by commas"
skills: "Linguistics PhD Student — UC Davis"
meta_author: Crowley Jordan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0097ff #d3d3d3
  primary-rgb: "0, 151, 255" #"211, 211, 211"
  secondary: 0d4f86 #009e37
  secondary-dark: 7a7a7a #000be7

# Footer settings
footer:
  copyright: JC
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/toowamba/
  - title: linkedin
    url: https://www.linkedin.com/in/jordan-crowley-006b55135/
  - title: github
    url: http://github.com/jacrowley-lin
  - title: researchgate
    url: https://www.researchgate.net/profile/Jordan_Crowley
  - title: ucdavis
    url: https://linguistics.ucdavis.edu/

# Postal address (add as many lines as necessary)
address:
  - line: 460 Kerr Hall
  - line: 1 Shields Avenue
  - line: Davis, CA 95616


# Credits content
credits: Github theme created by 'Freelancer' at <a href="http://startbootstrap.com">Bootstrap</a>.

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
